
windoze:
	rsync -a --exclude=".svn" ./ros_comm/ ${ROS_ROOT}/../ros_comm
	# now patched upstream
	# rsync -a --exclude=".svn" ./ros/ ${ROS_ROOT}
	# now using eros/tests/mingw_tests
	# rsync -a --exclude=".svn" ./ros_tutorials/ ${ROS_ROOT}/../ros_tutorials

.PHONY: windoze
