
windoze:
#	rsync -a --exclude=".svn" ./ros/ ${ROS_ROOT}
	rsync -a --exclude=".svn" ./ros_comm/ ${ROS_ROOT}/../ros_comm
	rsync -a --exclude=".svn" ./ros_tutorials/ ${ROS_ROOT}/../ros_tutorials

.PHONY: windoze
